# Generated by Django 4.0.2 on 2022-02-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='flatno',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='signup',
            name='street',
            field=models.CharField(max_length=255),
        ),
    ]
